apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eureka-admin
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      ekos-app: eureka-admin
  template:
    metadata:
      labels:
        ekos-app: eureka-admin
    spec:
      containers:
      - env:
        - name: DISCOVERY_SERVICE_NAME
          value: eureka
        image: registry.ekos.local/library/eureka-admin
        name: eureka-admin
        resources:
          limits:
            cpu: "1"
            memory: 1G
          requests:
            cpu: 500m
            memory: 500M
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-admin
  namespace: test
spec:
  ports:
  - name: "7020"
    port: 7020
    protocol: TCP
    targetPort: 7020
  selector:
    ekos-app: eureka-admin